#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : awesomeversion
Version  : 21.2.2
Release  : 2
URL      : https://files.pythonhosted.org/packages/2f/6f/2ec9d3603eb1331d32262025528ee1c7361f1ba8a7d87b922f30e6ac8d08/awesomeversion-21.2.2.tar.gz
Source0  : https://files.pythonhosted.org/packages/2f/6f/2ec9d3603eb1331d32262025528ee1c7361f1ba8a7d87b922f30e6ac8d08/awesomeversion-21.2.2.tar.gz
Summary  : One version package to rule them all, One version package to find them, One version package to bring them all, and in the darkness bind them.
Group    : Development/Tools
License  : MIT
Requires: awesomeversion-python = %{version}-%{release}
Requires: awesomeversion-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3

%description
# AwesomeVersion
[![codecov](https://codecov.io/gh/ludeeus/awesomeversion/branch/main/graph/badge.svg)](https://codecov.io/gh/ludeeus/awesomeversion)
![python version](https://img.shields.io/badge/Python-3.6=><=3.10-blue.svg)
![dependencies](https://img.shields.io/badge/Dependencies-0-blue.svg)
[![PyPI](https://img.shields.io/pypi/v/awesomeversion)](https://pypi.org/project/awesomeversion)
![Actions](https://github.com/ludeeus/awesomeversion/workflows/Actions/badge.svg?branch=main)

%package python
Summary: python components for the awesomeversion package.
Group: Default
Requires: awesomeversion-python3 = %{version}-%{release}

%description python
python components for the awesomeversion package.


%package python3
Summary: python3 components for the awesomeversion package.
Group: Default
Requires: python3-core
Provides: pypi(awesomeversion)

%description python3
python3 components for the awesomeversion package.


%prep
%setup -q -n awesomeversion-21.2.2
cd %{_builddir}/awesomeversion-21.2.2

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1612984718
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
