#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pypi-awesomeversion
Version  : 22.5.1
Release  : 26
URL      : https://files.pythonhosted.org/packages/59/80/2de22db5a7becd3fc23ede195e4323f2643a0e990166e632864d635348a3/awesomeversion-22.5.1.tar.gz
Source0  : https://files.pythonhosted.org/packages/59/80/2de22db5a7becd3fc23ede195e4323f2643a0e990166e632864d635348a3/awesomeversion-22.5.1.tar.gz
Summary  : One version package to rule them all, One version package to find them, One version package to bring them all, and in the darkness bind them.
Group    : Development/Tools
License  : MIT
Requires: pypi-awesomeversion-license = %{version}-%{release}
Requires: pypi-awesomeversion-python = %{version}-%{release}
Requires: pypi-awesomeversion-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pypi(poetry_core)

%description
# AwesomeVersion
[![codecov](https://codecov.io/gh/ludeeus/awesomeversion/branch/main/graph/badge.svg)](https://codecov.io/gh/ludeeus/awesomeversion)
![python version](https://img.shields.io/badge/Python-3.7=><=3.10-blue.svg)
![dependencies](https://img.shields.io/badge/Dependencies-0-blue.svg)
[![PyPI](https://img.shields.io/pypi/v/awesomeversion)](https://pypi.org/project/awesomeversion)
![Actions](https://github.com/ludeeus/awesomeversion/workflows/Actions/badge.svg?branch=main)

%package license
Summary: license components for the pypi-awesomeversion package.
Group: Default

%description license
license components for the pypi-awesomeversion package.


%package python
Summary: python components for the pypi-awesomeversion package.
Group: Default
Requires: pypi-awesomeversion-python3 = %{version}-%{release}

%description python
python components for the pypi-awesomeversion package.


%package python3
Summary: python3 components for the pypi-awesomeversion package.
Group: Default
Requires: python3-core
Provides: pypi(awesomeversion)

%description python3
python3 components for the pypi-awesomeversion package.


%prep
%setup -q -n awesomeversion-22.5.1
cd %{_builddir}/awesomeversion-22.5.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1652280676
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 -m build --wheel --skip-dependency-check --no-isolation

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-awesomeversion
cp %{_builddir}/awesomeversion-22.5.1/LICENCE.md %{buildroot}/usr/share/package-licenses/pypi-awesomeversion/daddaad606932154118c232a147f4c0c867bb5cf
pip install --root=%{buildroot} --no-deps --ignore-installed dist/*.whl
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-awesomeversion/daddaad606932154118c232a147f4c0c867bb5cf

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
