#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pypi-awesomeversion
Version  : 22.6.0
Release  : 30
URL      : https://files.pythonhosted.org/packages/60/4f/b8c3b64b9cd369d507769b6b0ad00760e0dde255fdaf870831a033f5c07e/awesomeversion-22.6.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/60/4f/b8c3b64b9cd369d507769b6b0ad00760e0dde255fdaf870831a033f5c07e/awesomeversion-22.6.0.tar.gz
Summary  : One version package to rule them all, One version package to find them, One version package to bring them all, and in the darkness bind them.
Group    : Development/Tools
License  : MIT
Requires: pypi-awesomeversion-license = %{version}-%{release}
Requires: pypi-awesomeversion-python = %{version}-%{release}
Requires: pypi-awesomeversion-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pypi(poetry_core)

%description
# AwesomeVersion
[![codecov](https://codecov.io/gh/ludeeus/awesomeversion/branch/main/graph/badge.svg)](https://codecov.io/gh/ludeeus/awesomeversion)
![python version](https://img.shields.io/badge/Python-3.7=><=3.10-blue.svg)
![dependencies](https://img.shields.io/badge/Dependencies-0-blue.svg)
[![PyPI](https://img.shields.io/pypi/v/awesomeversion)](https://pypi.org/project/awesomeversion)
![Actions](https://github.com/ludeeus/awesomeversion/workflows/Actions/badge.svg?branch=main)

%package license
Summary: license components for the pypi-awesomeversion package.
Group: Default

%description license
license components for the pypi-awesomeversion package.


%package python
Summary: python components for the pypi-awesomeversion package.
Group: Default
Requires: pypi-awesomeversion-python3 = %{version}-%{release}

%description python
python components for the pypi-awesomeversion package.


%package python3
Summary: python3 components for the pypi-awesomeversion package.
Group: Default
Requires: python3-core
Provides: pypi(awesomeversion)

%description python3
python3 components for the pypi-awesomeversion package.


%prep
%setup -q -n awesomeversion-22.6.0
cd %{_builddir}/awesomeversion-22.6.0
pushd ..
cp -a awesomeversion-22.6.0 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1656342470
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 -m build --wheel --skip-dependency-check --no-isolation
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 -msse2avx"
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 -msse2avx "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
python3 -m build --wheel --skip-dependency-check --no-isolation

popd

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-awesomeversion
cp %{_builddir}/awesomeversion-22.6.0/LICENCE.md %{buildroot}/usr/share/package-licenses/pypi-awesomeversion/daddaad606932154118c232a147f4c0c867bb5cf
pip install --root=%{buildroot} --no-deps --ignore-installed dist/*.whl
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
pip install --root=%{buildroot}-v3 --no-deps --ignore-installed dist/*.whl
popd
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-awesomeversion/daddaad606932154118c232a147f4c0c867bb5cf

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
